cmd: gulp test
targets:
    'Repositories: All':
        cmd: gulp test-repo
    'Repositories: MangaFox':
        cmd: gulp test-repo --repository MangaFox
    'Repositories: MockRepository':
        cmd: gulp test-repo --repository MockRepository
